---
# tasks file for app
    - name: Add user "Tomcat"
      user: name=tomcat createhome=yes
      become: true

    - name: Create a Tomcat Directory
      file:
        path: /opt/tomcat9
        owner: tomcat
        group: tomcat
        mode: 755
        recurse: yes

    - name: download & unarchive tomcat9
      unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.79/bin/apache-tomcat-9.0.79.tar.gz
        dest: /opt/tomcat9
        remote_src: yes
        extra_opts: [ --strip-components=1 ]

    - name: Change ownership of tomcat directory
      file:
        path: /opt/tomcat9
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory

    - name: Start Tomcat
      command: nohup /opt/tomcat9/bin/startup.sh
      become: true
      become_user: tomcat

    - name: wait for tomcat to start
      wait_for: port=8080

    - name: Transfer file from web to app
      synchronize:
        src: /home/nar/projects/target/hello-1.0.war
        dest: /opt/tomcat9/webapps/
      delegate_to: 158.160.116.246
      delegate_facts: true
