---
# tasks file for common
    - name: Update all Ubuntu packages
      apt:
         update_cache: yes
         cache_valid_time: 3600
    - name: Install JDK11 packages
      apt:
         name: openjdk-11-jdk
         state: present

    - name: Install Git
      apt:
         name: git
         state: present
