---
# tasks file for web
   - name: Install Apache Maven
     apt:
       name: maven
       state: present
   - name: Clone a github repository
     git:
       repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
       dest: /home/nar/projects/
       clone: yes
       update: yes
   - name: Running mvn package
     command: mvn clean install
     args:
        chdir: /home/nar/projects/
